FIND_PROGRAM(LCOV_EXECUTABLE lcov)
IF(LCOV_EXECUTABLE)
  MESSAGE("-- Found lcov: ${LCOV_EXECUTABLE}")
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --coverage")
  MESSAGE("CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS}")
ELSE()
  MESSAGE(FATAL_ERROR "-- lcov not found")
ENDIF()

FIND_PROGRAM(GENHTML_EXECUTABLE genhtml)
IF(GENHTML_EXECUTABLE)
  MESSAGE("-- Found genhtml: ${GENHTML_EXECUTABLE}")
ELSE()
  MESSAGE(FATAL_ERROR "-- genhtml not found")
ENDIF()

SET(CPP_COVERAGE_FILE ${CMAKE_BINARY_DIR}/lcov.info)
SEt(CPP_COVERAGE_OUTPUT_DIRECTORY
  ${CMAKE_BINARY_DIR}/htmlcov-cpp)

ADD_CUSTOM_TARGET(coverage
  COMMAND ${LCOV_EXECUTABLE}
  --capture
  --directory ${CMAKE_BINARY_DIR}
  --output-file=${CPP_COVERAGE_FILE}
  COMMAND ${GENHTML_EXECUTABLE}
  ${CPP_COVERAGE_FILE}
  --output-directory
  ${CPP_COVERAGE_OUTPUT_DIRECTORY}
  )
