FUNCTION(INITIALIZE_CACHE)
  SET(MFMG_ENABLE_CLANGFORMAT ${CMAKE_BUILD_TYPE} CACHE
    BOOL "Enable clang-format")
  SET(MFMG_ENABLE_COVERAGE ${MFMG_ENABLE_COVERAGE} CACHE
    BOOL "Enable test coverage")
  SET(MFMG_ENABLE_CUDA ${MFMG_ENABLE_CUDA} CACHE BOOL "Enable CUDA support")
  SET(MFMG_ENABLE_DOCUMENTATION ${MFMG_ENABLE_DOCUMENTATION} CACHE
    BOOL "Build ReadTheDocs documentation")
  SET(MFMG_ENABLE_STACKTRACE ${MFMG_ENABLE_STACKTRACE} CACHE
    BOOL "Enable stacktrace in assert")
  SET(MFMG_ENABLE_TESTS ${MFMG_ENABLE_TESTS} CACHE BOOL "Build tests")
ENDFUNCTION()
